<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="254585" started-at="2021-01-06T08:13:42Z" finished-at="2021-01-06T08:17:56Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="254585" started-at="2021-01-06T08:13:42Z" finished-at="2021-01-06T08:17:56Z">
      <class name="com.orangehrm.qa.testcases.TestCase_01">
        <test-method status="PASS" signature="init()[pri:0, instance:com.orangehrm.qa.testcases.TestCase_01@6093dd95]" name="init" is-config="true" duration-ms="52722" started-at="2021-01-06T13:43:43Z" finished-at="2021-01-06T13:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="throwq()[pri:0, instance:com.orangehrm.qa.testcases.TestCase_01@6093dd95]" name="throwq" is-config="true" duration-ms="86" started-at="2021-01-06T13:44:35Z" finished-at="2021-01-06T13:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- throwq -->
        <test-method status="PASS" signature="ValidLogin()[pri:0, instance:com.orangehrm.qa.testcases.TestCase_01@6093dd95]" name="ValidLogin" duration-ms="124687" started-at="2021-01-06T13:44:35Z" finished-at="2021-01-06T13:46:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLogin -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.orangehrm.qa.testcases.TestCase_01@6093dd95]" name="teardown" is-config="true" duration-ms="59" started-at="2021-01-06T13:46:40Z" finished-at="2021-01-06T13:46:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.orangehrm.qa.testcases.TestCase_01 -->
      <class name="com.orangehrm.qa.testcases.Ddtests">
        <test-method status="PASS" signature="init()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="init" is-config="true" duration-ms="43980" started-at="2021-01-06T13:46:40Z" finished-at="2021-01-06T13:47:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="init2()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="init2" is-config="true" duration-ms="6" started-at="2021-01-06T13:47:26Z" finished-at="2021-01-06T13:47:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init2 -->
        <test-method status="PASS" signature="temp(java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="temp" duration-ms="14259" started-at="2021-01-06T13:47:26Z" data-provider="test2data" finished-at="2021-01-06T13:47:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- temp -->
        <test-method status="PASS" signature="init2()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="init2" is-config="true" duration-ms="9" started-at="2021-01-06T13:47:40Z" finished-at="2021-01-06T13:47:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init2 -->
        <test-method status="FAIL" signature="temp(java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="temp" duration-ms="3257" started-at="2021-01-06T13:47:40Z" data-provider="test2data" finished-at="2021-01-06T13:47:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[harish]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[harish123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.orangehrm.qa.testcases.Ddtests.temp(Ddtests.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- temp -->
        <test-method status="PASS" signature="init2()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="init2" is-config="true" duration-ms="5" started-at="2021-01-06T13:47:44Z" finished-at="2021-01-06T13:47:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init2 -->
        <test-method status="FAIL" signature="temp(java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="temp" duration-ms="3993" started-at="2021-01-06T13:47:44Z" data-provider="test2data" finished-at="2021-01-06T13:47:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[fake]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[fake123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.orangehrm.qa.testcases.Ddtests.temp(Ddtests.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- temp -->
        <test-method status="PASS" signature="init2()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="init2" is-config="true" duration-ms="6" started-at="2021-01-06T13:47:49Z" finished-at="2021-01-06T13:47:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init2 -->
        <test-method status="FAIL" signature="temp(java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="temp" duration-ms="2813" started-at="2021-01-06T13:47:49Z" data-provider="test2data" finished-at="2021-01-06T13:47:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[fake2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[321ekaf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.orangehrm.qa.testcases.Ddtests.temp(Ddtests.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- temp -->
        <test-method status="PASS" signature="init2()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="init2" is-config="true" duration-ms="4" started-at="2021-01-06T13:47:52Z" finished-at="2021-01-06T13:47:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init2 -->
        <test-method status="PASS" signature="temp(java.lang.String, java.lang.String)[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="temp" duration-ms="3954" started-at="2021-01-06T13:47:52Z" data-provider="test2data" finished-at="2021-01-06T13:47:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- temp -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.orangehrm.qa.testcases.Ddtests@5622fdf]" name="teardown" is-config="true" duration-ms="66" started-at="2021-01-06T13:47:56Z" finished-at="2021-01-06T13:47:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.orangehrm.qa.testcases.Ddtests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
